/**
 * Approved SYNTHETIC knowledge base for Endpoint 3 (/assistant) ONLY.
 *
 * This is general, non-personal, illustrative information about water services,
 * digital water tools, and this feedback project. It contains NO participant
 * data and NO real local facts (no named authorities, NGOs, phone numbers or
 * procedures). The assistant must answer only from this approved context.
 *
 * Arabic text is indicative and should be reviewed by a native speaker and the
 * research/ethics team before any real use (same policy as the survey wording).
 */
export type KbCategory =
  | "water_context"
  | "digital_tools_context"
  | "project_context"
  | "confidentiality_context";

export interface KbEntry {
  id: string;
  category: KbCategory;
  keywords: string[]; // salient retrieval terms (EN + AR)
  en: string;
  ar: string;
}

export const KNOWLEDGE: KbEntry[] = [
  // ── water_context ──
  { id: "w1", category: "water_context", keywords: ["supply", "access", "network", "إمداد", "وصول"],
    en: "Water supply means how households receive water — through a piped network, shared points, or delivery. Many areas receive water on a schedule rather than continuously.",
    ar: "إمداد المياه يعني كيفية حصول الأسر على المياه — عبر شبكة أنابيب أو نقاط مشتركة أو التوصيل. تحصل مناطق كثيرة على المياه وفق جدول وليس بشكل مستمر." },
  { id: "w2", category: "water_context", keywords: ["shortage", "scarcity", "نقص", "شح", "ندرة"],
    en: "Water scarcity is common in arid regions, and supply can be limited or irregular. The project asks residents about their day-to-day experience of water availability.",
    ar: "ندرة المياه شائعة في المناطق الجافة، وقد يكون الإمداد محدودًا أو غير منتظم. يسأل المشروع السكان عن تجربتهم اليومية مع توفر المياه." },
  { id: "w3", category: "water_context", keywords: ["schedule", "intermittent", "timing", "جدول", "متقطع", "توقيت"],
    en: "Where water arrives on a schedule, households often store it for later use. Knowing when water usually arrives helps people plan storage.",
    ar: "حين تصل المياه وفق جدول، غالبًا ما تخزّنها الأسر للاستخدام لاحقًا. معرفة موعد وصول المياه عادةً يساعد الناس على التخطيط للتخزين." },
  { id: "w4", category: "water_context", keywords: ["tanker", "truck", "delivery", "صهريج", "تنكر", "توصيل"],
    en: "Some households rely on water delivered by tanker trucks. Tanker water is a general topic the survey may ask about, including cost and reliability.",
    ar: "تعتمد بعض الأسر على المياه التي تُنقل بالصهاريج. مياه الصهاريج موضوع عام قد يسأل عنه الاستبيان، بما في ذلك التكلفة والموثوقية." },
  { id: "w5", category: "water_context", keywords: ["tank", "storage", "rooftop", "خزان", "تخزين", "سطح"],
    en: "Storage tanks (for example on rooftops) hold water between supply periods. Tank size and cleanliness can affect how much water a household has available.",
    ar: "تحفظ خزانات التخزين (مثلًا على الأسطح) المياه بين فترات الإمداد. يمكن أن يؤثر حجم الخزان ونظافته على كمية المياه المتاحة للأسرة." },
  { id: "w6", category: "water_context", keywords: ["pressure", "low pressure", "ضغط", "ضعف الضغط"],
    en: "Low water pressure can make it hard to fill tanks or use taps normally. Describing where and when pressure is low can help when reporting a problem.",
    ar: "قد يصعّب ضعف ضغط المياه ملء الخزانات أو استخدام الصنابير بشكل طبيعي. وصف مكان وزمان ضعف الضغط يساعد عند الإبلاغ عن مشكلة." },
  { id: "w7", category: "water_context", keywords: ["quality", "color", "turbid", "dirty", "discolored", "جودة", "لون", "عكارة", "وسخ"],
    en: "Water can sometimes look unusual in colour, smell, or clarity. This assistant cannot assess the cause or say whether it is safe. The project collects general feedback about water-quality experiences.",
    ar: "قد تبدو المياه أحيانًا غير معتادة في اللون أو الرائحة أو الصفاء. لا يستطيع هذا المساعد تقييم السبب أو تحديد ما إذا كانت آمنة. ويجمع المشروع آراء عامة حول تجارب جودة المياه." },
  { id: "w8", category: "water_context", keywords: ["taste", "salty", "طعم", "مالح", "ملوحة"],
    en: "Some residents report salty or unusual taste in their water. This is general feedback the project collects; it is not medical guidance.",
    ar: "يبلّغ بعض السكان عن طعم مالح أو غير معتاد في مياههم. هذه ملاحظات عامة يجمعها المشروع، وليست إرشادًا طبيًا." },
  { id: "w9", category: "water_context", keywords: ["smell", "odor", "رائحة"],
    en: "An unusual smell is something residents sometimes notice in their water supply. The survey records such observations in general terms only.",
    ar: "الرائحة غير المعتادة شيء يلاحظه السكان أحيانًا في إمداد مياههم. يسجّل الاستبيان هذه الملاحظات بشكل عام فقط." },
  { id: "w10", category: "water_context", keywords: ["drinking", "safe", "شرب", "آمن"],
    en: "Whether water is suitable for drinking is decided by the responsible water authority and testing — not by this assistant. The project only gathers residents' experiences.",
    ar: "ما إذا كانت المياه صالحة للشرب تقرره الجهة المسؤولة عن المياه والفحوصات — وليس هذا المساعد. يكتفي المشروع بجمع تجارب السكان." },
  { id: "w11", category: "water_context", keywords: ["leak", "pipe", "burst", "تسرب", "أنبوب", "كسر"],
    en: "Leaks waste water and can reduce supply. Useful details when reporting a leak are the area, when it started, and what you observed — without any personal information.",
    ar: "التسربات تهدر المياه وقد تقلّل الإمداد. التفاصيل المفيدة عند الإبلاغ عن تسرب هي المنطقة ووقت بدئه وما لاحظته — دون أي معلومات شخصية." },
  { id: "w12", category: "water_context", keywords: ["bill", "billing", "charge", "فاتورة", "فواتير", "رسوم"],
    en: "Water bills and charges are a common concern. The survey may ask whether billing information is clear; it does not handle payments or disputes.",
    ar: "الفواتير ورسوم المياه مصدر قلق شائع. قد يسأل الاستبيان عمّا إذا كانت معلومات الفواتير واضحة؛ وهو لا يتعامل مع المدفوعات أو الاعتراضات." },
  { id: "w13", category: "water_context", keywords: ["meter", "عداد"],
    en: "Water meters measure how much water is used. Some residents have questions about meter readings; the survey captures whether such information is accessible.",
    ar: "تقيس عدّادات المياه كمية المياه المستخدمة. لدى بعض السكان أسئلة حول قراءات العدّاد؛ ويرصد الاستبيان مدى توفّر هذه المعلومات." },
  { id: "w14", category: "water_context", keywords: ["sewage", "wastewater", "drain", "صرف", "مجاري", "تصريف"],
    en: "Wastewater and drainage issues are related to water services. The project focuses on water supply and digital reporting, and notes related concerns generally.",
    ar: "ترتبط مشكلات الصرف الصحي والتصريف بخدمات المياه. يركّز المشروع على إمداد المياه والإبلاغ الرقمي، ويسجّل المخاوف ذات الصلة بشكل عام." },
  { id: "w15", category: "water_context", keywords: ["outage", "cut", "interruption", "انقطاع", "قطع"],
    en: "A water cut-off (outage) is when supply stops for a period. Reporting when and where an outage happened helps services understand the problem.",
    ar: "انقطاع المياه هو توقّف الإمداد لفترة. الإبلاغ عن زمان ومكان الانقطاع يساعد الجهات على فهم المشكلة." },
  { id: "w16", category: "water_context", keywords: ["describe", "describing", "problem", "water problem", "what details", "report details", "وصف", "يصف", "مشكلة المياه", "تفاصيل"],
    en: "A short, general description of the issue, the area, and when you noticed it is usually enough. Clear general details can help describe the issue without identifying you — do not include your name, phone number, exact address, or ID number.",
    ar: "عادةً ما يكفي وصف قصير وعام للمشكلة والمنطقة ووقت ملاحظتها. يمكن للتفاصيل العامة الواضحة أن تساعد في وصف المشكلة دون التعرّف عليك — لا تُضمّن اسمك أو رقم هاتفك أو عنوانك الدقيق أو رقم هويتك." },
  { id: "w17", category: "water_context", keywords: ["reporting", "channel", "how to report", "إبلاغ", "تبليغ", "قناة"],
    en: "Water problems are usually reported to the responsible water provider or local service, through their official channels. This assistant cannot file reports for you.",
    ar: "تُبلَّغ مشكلات المياه عادةً إلى مزوّد المياه المسؤول أو الخدمة المحلية عبر قنواتهم الرسمية. لا يستطيع هذا المساعد تقديم بلاغات نيابةً عنك." },
  { id: "w18", category: "water_context", keywords: ["conserve", "conservation", "save water", "saving", "preserve", "reduce", "ترشيد", "توفير", "حفظ المياه", "توعيه"],
    en: "Where water is limited, being generally aware of how water is used and reporting leaks early can help. This is broad awareness only — the assistant does not give official conservation instructions or personalised advice.",
    ar: "حيث تكون المياه محدودة، قد يساعد الوعي العام بكيفية استخدام المياه والإبلاغ المبكر عن التسربات. هذه توعية عامة فقط — ولا يقدّم المساعد تعليمات رسمية لترشيد المياه أو نصائح شخصية." },
  { id: "w19", category: "water_context", keywords: ["shared", "communal", "point", "مشترك", "نقطة عامة"],
    en: "Some communities use shared water points rather than individual household connections. Access and waiting time at shared points are relevant survey topics.",
    ar: "تستخدم بعض المجتمعات نقاط مياه مشتركة بدلًا من توصيلات منزلية فردية. يُعدّ الوصول ووقت الانتظار في النقاط المشتركة من مواضيع الاستبيان." },
  { id: "w20", category: "water_context", keywords: ["seasonal", "summer", "demand", "موسمي", "صيف", "طلب"],
    en: "Water demand often rises in hot seasons, which can strain supply. The survey gathers residents' experiences across different conditions.",
    ar: "يرتفع الطلب على المياه غالبًا في المواسم الحارة، ما قد يضغط على الإمداد. يجمع الاستبيان تجارب السكان في ظروف مختلفة." },

  // ── digital_tools_context ──
  { id: "d1", category: "digital_tools_context", keywords: ["digital tools", "app", "online", "أدوات رقمية", "تطبيق", "إلكتروني"],
    en: "Digital water tools include mobile apps, websites, SMS and messaging services used to get water information or report problems. The project studies how usable these are.",
    ar: "تشمل أدوات المياه الرقمية تطبيقات الهاتف والمواقع والرسائل النصية وخدمات المراسلة المستخدمة للحصول على معلومات المياه أو الإبلاغ عن المشكلات. يدرس المشروع مدى سهولة استخدامها." },
  { id: "d2", category: "digital_tools_context", keywords: ["mobile app", "application", "تطبيق الهاتف"],
    en: "A mobile app can let residents report issues or check updates. Apps vary in language support and ease of use, which the survey asks about.",
    ar: "يمكن لتطبيق الهاتف أن يتيح للسكان الإبلاغ عن المشكلات أو متابعة التحديثات. تختلف التطبيقات في دعم اللغة وسهولة الاستخدام، وهو ما يسأل عنه الاستبيان." },
  { id: "d3", category: "digital_tools_context", keywords: ["whatsapp", "messaging", "واتساب", "مراسلة"],
    en: "WhatsApp and similar messaging apps are sometimes used to send reports or receive updates because they are familiar and low-cost.",
    ar: "يُستخدم واتساب وتطبيقات المراسلة المشابهة أحيانًا لإرسال البلاغات أو تلقّي التحديثات لأنها مألوفة ومنخفضة التكلفة." },
  { id: "d4", category: "digital_tools_context", keywords: ["sms", "text message", "رسالة نصية"],
    en: "SMS text messages work on basic phones and without internet, which can make them useful for updates where connectivity is limited.",
    ar: "تعمل الرسائل النصية SMS على الهواتف البسيطة ودون إنترنت، ما قد يجعلها مفيدة للتحديثات حيث يكون الاتصال محدودًا." },
  { id: "d5", category: "digital_tools_context", keywords: ["website", "portal", "موقع", "بوابة"],
    en: "A website or portal can provide information about water services. Websites need internet access and can be harder to use on small screens.",
    ar: "يمكن لموقع أو بوابة إلكترونية تقديم معلومات عن خدمات المياه. تحتاج المواقع إلى إنترنت وقد يصعب استخدامها على الشاشات الصغيرة." },
  { id: "d6", category: "digital_tools_context", keywords: ["phone call", "call", "مكالمة", "اتصال"],
    en: "Phone calls are a non-digital way to report problems. The project compares digital channels with familiar options like calling.",
    ar: "المكالمات الهاتفية وسيلة غير رقمية للإبلاغ عن المشكلات. يقارن المشروع القنوات الرقمية بالخيارات المألوفة مثل الاتصال." },
  { id: "d7", category: "digital_tools_context", keywords: ["alert", "notification", "outage alert", "تنبيه", "إشعار"],
    en: "Alerts or notifications can tell residents about water cut-offs or schedules in advance. Whether people receive and trust such alerts is a survey topic.",
    ar: "يمكن للتنبيهات أو الإشعارات إخبار السكان بانقطاعات المياه أو الجداول مسبقًا. ومدى تلقّي الناس لهذه التنبيهات وثقتهم بها من مواضيع الاستبيان." },
  { id: "d8", category: "digital_tools_context", keywords: ["billing app", "online billing", "فاتورة إلكترونية"],
    en: "Some tools show billing information digitally. Clear digital billing can help, but only if it is understandable and in the user's language.",
    ar: "تعرض بعض الأدوات معلومات الفواتير رقميًا. يمكن أن تساعد الفوترة الرقمية الواضحة، لكن فقط إذا كانت مفهومة وبلغة المستخدم." },
  { id: "d9", category: "digital_tools_context", keywords: ["internet", "connectivity", "offline", "إنترنت", "اتصال", "دون اتصال"],
    en: "Limited or unreliable internet is a common barrier to using digital tools. Tools that work offline or over SMS can help where connectivity is weak.",
    ar: "الإنترنت المحدود أو غير الموثوق عائق شائع أمام استخدام الأدوات الرقمية. الأدوات التي تعمل دون اتصال أو عبر الرسائل النصية قد تساعد حيث يكون الاتصال ضعيفًا." },
  { id: "d10", category: "digital_tools_context", keywords: ["data cost", "mobile data", "تكلفة البيانات", "باقة"],
    en: "The cost of mobile data can stop people from using apps or websites. This is one of the barriers the project asks residents about.",
    ar: "قد تمنع تكلفة بيانات الهاتف الناس من استخدام التطبيقات أو المواقع. وهذا أحد العوائق التي يسأل عنها المشروع." },
  { id: "d11", category: "digital_tools_context", keywords: ["device", "old phone", "smartphone", "جهاز", "هاتف قديم"],
    en: "Not everyone has a suitable smartphone, and older devices may not run newer apps. Device limitations affect who can use digital tools.",
    ar: "لا يملك الجميع هاتفًا ذكيًا مناسبًا، وقد لا تشغّل الأجهزة الأقدم التطبيقات الأحدث. تؤثر قيود الأجهزة على من يستطيع استخدام الأدوات الرقمية." },
  { id: "d12", category: "digital_tools_context", keywords: ["literacy", "digital literacy", "reading", "أمية", "قراءة", "مهارات رقمية"],
    en: "Reading, writing, or digital-literacy difficulties can make apps hard to use. Simple language and clear steps help more people take part.",
    ar: "قد تجعل صعوبات القراءة أو الكتابة أو المهارات الرقمية استخدام التطبيقات صعبًا. تساعد اللغة البسيطة والخطوات الواضحة مزيدًا من الناس على المشاركة." },
  { id: "d13", category: "digital_tools_context", keywords: ["language", "arabic", "english", "لغة", "عربية", "إنجليزية"],
    en: "Tools that are not available in the user's language are harder to use. This project supports Arabic and English so more residents can take part.",
    ar: "الأدوات غير المتوفرة بلغة المستخدم أصعب في الاستخدام. يدعم هذا المشروع العربية والإنجليزية ليتمكّن مزيد من السكان من المشاركة." },
  { id: "d14", category: "digital_tools_context", keywords: ["trust", "reliable", "digital trust", "ثقة", "موثوق"],
    en: "People use digital reporting more when they trust it will be handled responsibly and lead to action. Trust is a key theme in the survey.",
    ar: "يستخدم الناس الإبلاغ الرقمي أكثر عندما يثقون بأنه سيُعالَج بمسؤولية ويؤدي إلى إجراء. الثقة موضوع رئيسي في الاستبيان." },
  { id: "d15", category: "digital_tools_context", keywords: ["privacy", "data privacy", "خصوصية البيانات"],
    en: "Privacy concerns can stop people from sharing information digitally. Good tools explain what data they collect and keep it to a minimum.",
    ar: "قد تمنع مخاوف الخصوصية الناس من مشاركة المعلومات رقميًا. توضّح الأدوات الجيدة البيانات التي تجمعها وتُبقيها عند الحد الأدنى." },
  { id: "d16", category: "digital_tools_context", keywords: ["accessibility", "easy to use", "وصول", "سهولة"],
    en: "Accessible tools use large buttons, plain language, and work on low-end phones and slow connections, so more people can use them.",
    ar: "تستخدم الأدوات سهلة الوصول أزرارًا كبيرة ولغة بسيطة وتعمل على الهواتف البسيطة والاتصالات البطيئة، ليتمكّن مزيد من الناس من استخدامها." },
  { id: "d17", category: "digital_tools_context", keywords: ["save offline", "send later", "حفظ", "إرسال لاحقًا"],
    en: "Some tools let you record a report while offline and send it once you have a connection, which helps in areas with weak internet.",
    ar: "تتيح بعض الأدوات تسجيل بلاغ دون اتصال وإرساله عند توفّر الاتصال، ما يساعد في المناطق ذات الإنترنت الضعيف." },
  { id: "d18", category: "digital_tools_context", keywords: ["complicated", "complex", "confusing", "معقّد", "مربك"],
    en: "If a tool has too many steps or confusing screens, people may give up. The survey asks whether tools are too complicated to use.",
    ar: "إذا كان للأداة خطوات كثيرة أو شاشات مربكة، فقد يستسلم الناس. يسأل الاستبيان عمّا إذا كانت الأدوات معقّدة جدًا للاستخدام." },
  { id: "d19", category: "digital_tools_context", keywords: ["improve", "benefit", "advantage", "تحسين", "فائدة"],
    en: "Digital tools can speed up reporting, share outage alerts, and make billing clearer — when they are accessible and trusted.",
    ar: "يمكن للأدوات الرقمية تسريع الإبلاغ ومشاركة تنبيهات الانقطاع وجعل الفوترة أوضح — عندما تكون متاحة وموثوقة." },
  { id: "d20", category: "digital_tools_context", keywords: ["limitation", "drawback", "حدود", "عيوب"],
    en: "Digital tools are not a complete solution: they depend on devices, internet, literacy and trust, and cannot replace the underlying water service.",
    ar: "ليست الأدوات الرقمية حلًا كاملًا: فهي تعتمد على الأجهزة والإنترنت والمهارات والثقة، ولا يمكنها أن تحل محل خدمة المياه نفسها." },

  // ── project_context ──
  { id: "p1", category: "project_context", keywords: ["project", "what is this", "مشروع", "ما هذا"],
    en: "This is an academic research project that collects feedback from residents in Jordan about digital technology in water management. It is not a water provider or an aid service.",
    ar: "هذا مشروع بحثي أكاديمي يجمع آراء السكان في الأردن حول التكنولوجيا الرقمية في إدارة المياه. وهو ليس مزوّد مياه ولا جهة إغاثة." },
  { id: "p2", category: "project_context", keywords: ["aim", "purpose", "goal", "هدف", "غرض"],
    en: "The aim is to learn how useful and usable a bilingual chatbot survey is for collecting this kind of feedback, especially for refugees and other communities.",
    ar: "الهدف هو معرفة مدى فائدة وسهولة استخدام استبيان عبر روبوت محادثة ثنائي اللغة في جمع هذا النوع من الآراء، خاصةً للاجئين والمجتمعات الأخرى." },
  { id: "p3", category: "project_context", keywords: ["who runs", "researchers", "academic", "من يدير", "باحثون"],
    en: "It is run as an academic study by a research team. The assistant does not represent any government, water company, NGO, the UN, or a university officially.",
    ar: "يُدار كدراسة أكاديمية من فريق بحثي. ولا يمثّل المساعد أي حكومة أو شركة مياه أو منظمة غير حكومية أو الأمم المتحدة أو جامعة بصفة رسمية." },
  { id: "p4", category: "project_context", keywords: ["collect", "what data", "يجمع", "بيانات"],
    en: "The survey collects answers about water-technology themes plus broad demographic bands (like age range and area). It does not collect names, phone numbers or exact addresses.",
    ar: "يجمع الاستبيان إجابات حول محاور تكنولوجيا المياه إضافةً إلى فئات ديموغرافية عامة (مثل الفئة العمرية والمنطقة). ولا يجمع الأسماء أو أرقام الهواتف أو العناوين الدقيقة." },
  { id: "p5", category: "project_context", keywords: ["themes", "topics", "محاور", "مواضيع"],
    en: "The survey covers five themes: accessibility of tools, trust and willingness, relevance, challenges, and impact of reporting water issues.",
    ar: "يغطّي الاستبيان خمسة محاور: سهولة الوصول إلى الأدوات، والثقة والاستعداد، والفائدة، والتحديات، وأثر الإبلاغ عن مشكلات المياه." },
  { id: "p6", category: "project_context", keywords: ["instrument", "data collection", "أداة", "جمع البيانات"],
    en: "The resident chatbot is only a data-collection instrument. It asks approved questions and records answers; it does not chat freely or give advice.",
    ar: "روبوت السكان هو مجرد أداة لجمع البيانات. يطرح أسئلة معتمدة ويسجّل الإجابات؛ ولا يحاور بحرية ولا يقدّم نصائح." },
  { id: "p7", category: "project_context", keywords: ["no advice", "not advice", "لا نصيحة", "ليست نصيحة"],
    en: "Neither the survey nor this assistant gives advice, recommendations or promises of action. They provide general information and collect feedback only.",
    ar: "لا يقدّم الاستبيان ولا هذا المساعد نصائح أو توصيات أو وعودًا بالتنفيذ. فهما يقدّمان معلومات عامة ويجمعان الآراء فقط." },
  { id: "p8", category: "project_context", keywords: ["voluntary", "consent", "طوعي", "موافقة"],
    en: "Taking part in the survey is voluntary and begins with informed consent. Residents can skip any question or stop at any time.",
    ar: "المشاركة في الاستبيان طوعية وتبدأ بموافقة مستنيرة. ويمكن للسكان تخطّي أي سؤال أو التوقف في أي وقت." },
  { id: "p9", category: "project_context", keywords: ["skip", "stop", "withdraw", "تخطّي", "إيقاف", "انسحاب"],
    en: "During the survey you can skip a question, go back, or stop entirely. Stopping is always available and does not require a reason.",
    ar: "أثناء الاستبيان يمكنك تخطّي سؤال أو الرجوع أو التوقف تمامًا. الإيقاف متاح دائمًا ولا يتطلب سببًا." },
  { id: "p10", category: "project_context", keywords: ["use feedback", "how used", "استخدام الآراء", "كيف تُستخدم"],
    en: "Feedback is used by researchers in anonymised form to understand experiences and to evaluate the chatbot method. Individual people are not identified.",
    ar: "يستخدم الباحثون الآراء بشكل مجهول الهوية لفهم التجارب وتقييم أسلوب روبوت المحادثة. ولا يتم التعرّف على الأفراد." },
  { id: "p11", category: "project_context", keywords: ["analysis", "phase 2", "research output", "تحليل", "المرحلة الثانية"],
    en: "Later analysis looks for common themes across anonymised answers to support research findings. It works on aggregated, de-identified data.",
    ar: "ينظر التحليل اللاحق في المواضيع المشتركة عبر الإجابات المجهولة لدعم نتائج البحث. ويعمل على بيانات مجمّعة ومجرّدة من الهوية." },
  { id: "p12", category: "project_context", keywords: ["who sees", "access", "من يرى", "اطّلاع"],
    en: "Only the authorised research team can see the collected answers. This assistant is separate and cannot see any survey responses.",
    ar: "يستطيع فريق البحث المخوّل وحده الاطّلاع على الإجابات المجمّعة. وهذا المساعد منفصل ولا يمكنه رؤية أي إجابات للاستبيان." },
  { id: "p13", category: "project_context", keywords: ["assistant can", "capabilities", "يستطيع المساعد", "قدرات"],
    en: "This assistant can explain general water-service topics, digital water tools, and how the feedback project works — using approved information only.",
    ar: "يستطيع هذا المساعد شرح مواضيع خدمات المياه العامة وأدوات المياه الرقمية وكيفية عمل مشروع الآراء — باستخدام معلومات معتمدة فقط." },
  { id: "p14", category: "project_context", keywords: ["assistant cannot", "limits", "لا يستطيع المساعد", "حدود"],
    en: "This assistant cannot file reports, look up your account, contact authorities, give advice, or access any participant's survey answers.",
    ar: "لا يستطيع هذا المساعد تقديم بلاغات أو الاطّلاع على حسابك أو الاتصال بالجهات أو تقديم نصائح أو الوصول إلى إجابات أي مشارك." },
  { id: "p15", category: "project_context", keywords: ["give feedback", "participate", "تقديم رأي", "مشاركة"],
    en: "To give feedback about water services, use the survey itself — not this assistant. The assistant is only for general information.",
    ar: "لتقديم رأيك حول خدمات المياه، استخدم الاستبيان نفسه — وليس هذا المساعد. فالمساعد مخصّص للمعلومات العامة فقط." },

  // ── confidentiality_context ──
  { id: "c1", category: "confidentiality_context", keywords: ["anonymous", "pseudonymous", "مجهول", "هوية"],
    en: "The survey is anonymous: it uses a random session identifier and is not linked to your identity.",
    ar: "الاستبيان مجهول الهوية: يستخدم معرّف جلسة عشوائيًا ولا يُربط بهويتك." },
  { id: "c2", category: "confidentiality_context", keywords: ["name", "do not share name", "اسم", "لا تشارك الاسم"],
    en: "Please do not share your name. The project does not need it, and you should not type it into the survey or this assistant.",
    ar: "يُرجى عدم مشاركة اسمك. لا يحتاجه المشروع، ولا ينبغي كتابته في الاستبيان أو في هذا المساعد." },
  { id: "c3", category: "confidentiality_context", keywords: ["phone", "number", "هاتف", "رقم"],
    en: "Please do not share phone numbers. The project collects no contact details and cannot call or message you.",
    ar: "يُرجى عدم مشاركة أرقام الهواتف. لا يجمع المشروع أي بيانات تواصل ولا يمكنه الاتصال بك أو مراسلتك." },
  { id: "c4", category: "confidentiality_context", keywords: ["address", "location", "gps", "عنوان", "موقع"],
    en: "Please do not share your exact address or location. A general area (such as a city or district) is enough for the survey.",
    ar: "يُرجى عدم مشاركة عنوانك أو موقعك الدقيق. تكفي المنطقة العامة (مثل المدينة أو الحي) للاستبيان." },
  { id: "c5", category: "confidentiality_context", keywords: ["id", "passport", "identity number", "هوية", "جواز", "رقم وطني"],
    en: "Please do not share ID, passport, or registration numbers. The project never needs them.",
    ar: "يُرجى عدم مشاركة أرقام الهوية أو الجواز أو التسجيل. لا يحتاجها المشروع إطلاقًا." },
  { id: "c6", category: "confidentiality_context", keywords: ["demographic", "age band", "why ask", "ديموغرافيا", "فئة عمرية", "لماذا"],
    en: "The survey asks for broad bands (like an age range and general area) instead of exact details, so answers stay useful for research but cannot identify you.",
    ar: "يطلب الاستبيان فئات عامة (مثل نطاق عمري ومنطقة عامة) بدلًا من التفاصيل الدقيقة، لتبقى الإجابات مفيدة للبحث دون أن تتعرّف عليك." },
  { id: "c7", category: "confidentiality_context", keywords: ["gender", "prefer not to say", "نوع اجتماعي", "أفضّل عدم الإجابة"],
    en: "Sensitive questions such as gender are optional and include a 'prefer not to say' choice.",
    ar: "الأسئلة الحساسة مثل النوع الاجتماعي اختيارية وتتضمّن خيار 'أفضّل عدم الإجابة'." },
  { id: "c8", category: "confidentiality_context", keywords: ["secure", "encrypted", "storage", "آمن", "تشفير", "تخزين"],
    en: "Collected answers are stored securely and seen only by the research team. Free-text answers are also scrubbed of obvious personal details.",
    ar: "تُخزَّن الإجابات المجمّعة بأمان ولا يطّلع عليها سوى فريق البحث. كما تُنقّى الإجابات النصية من التفاصيل الشخصية الواضحة." },
  { id: "c9", category: "confidentiality_context", keywords: ["minimisation", "minimal data", "تقليل البيانات", "حد أدنى"],
    en: "The project follows data minimisation: it collects only what the research needs and nothing that could directly identify a person.",
    ar: "يتبع المشروع مبدأ تقليل البيانات: يجمع فقط ما يحتاجه البحث ولا شيء يمكن أن يعرّف الشخص مباشرةً." },
  { id: "c10", category: "confidentiality_context", keywords: ["delete", "withdraw data", "حذف", "سحب البيانات"],
    en: "Participants can ask for their responses to be removed. The thank-you page explains how to contact the research team about withdrawal.",
    ar: "يمكن للمشاركين طلب إزالة إجاباتهم. وتوضّح صفحة الشكر كيفية التواصل مع فريق البحث بشأن الانسحاب." },
  { id: "c11", category: "confidentiality_context", keywords: ["assistant no access", "isolated", "لا وصول", "معزول"],
    en: "This assistant has no access to participant survey answers, sessions, demographics, consent records, or any dashboard data. It is fully separated.",
    ar: "لا يملك هذا المساعد أي وصول إلى إجابات المشاركين أو الجلسات أو البيانات الديموغرافية أو سجلات الموافقة أو أي بيانات لوحة التحكم. وهو منفصل تمامًا." },
  { id: "c12", category: "confidentiality_context", keywords: ["safe", "what to share", "آمن", "ماذا أشارك"],
    en: "It is safe to ask general questions here. Just keep them general and do not include personal or contact details in your messages.",
    ar: "من الآمن طرح أسئلة عامة هنا. فقط أبقِها عامة ولا تُضمّن تفاصيل شخصية أو بيانات تواصل في رسائلك." },

  // ── added: deeper water coverage ──
  { id: "w21", category: "water_context", keywords: ["rotation", "rationing", "days", "تناوب", "أيام", "توزيع"],
    en: "In some areas water is supplied on a rotation, so different neighbourhoods receive it on different days. Receiving water only on certain days can be normal where supply is limited.",
    ar: "في بعض المناطق تُوزَّع المياه بالتناوب، فتحصل الأحياء المختلفة عليها في أيام مختلفة. وقد يكون استلام المياه في أيام معيّنة فقط أمرًا معتادًا حيث يكون الإمداد محدودًا." },
  { id: "w22", category: "water_context", keywords: ["enough", "quantity", "amount", "insufficient", "كمية", "كافية", "تكفي"],
    en: "Some households feel the amount of water they receive is not enough for their needs. The survey asks about how available and sufficient water is, without telling households how to manage it.",
    ar: "تشعر بعض الأسر بأن كمية المياه التي تتلقاها لا تكفي احتياجاتها. ويسأل الاستبيان عن مدى توفّر المياه وكفايتها دون إخبار الأسر بكيفية إدارتها." },
  { id: "w23", category: "water_context", keywords: ["cloudy", "turbid", "discolored", "dirty", "safe", "عكر", "عكاره", "لون", "وسخ", "سلامه"],
    en: "If water looks cloudy or discoloured, whether it is safe is decided by the responsible water authority and proper testing. This assistant does not assess safety or health effects.",
    ar: "إذا بدت المياه عكرة أو متغيّرة اللون، فإن سلامتها تقررها الجهة المسؤولة عن المياه والفحوصات المناسبة. ولا يقيّم هذا المساعد السلامة أو الآثار الصحية." },
  { id: "w24", category: "water_context", keywords: ["hard water", "limescale", "particles", "scale", "عسره", "ترسبات", "جزيئات"],
    en: "White particles or scale can appear with hard water in some areas. This is general information; questions about water treatment should go to the responsible authority.",
    ar: "قد تظهر جزيئات بيضاء أو ترسبات مع المياه العسرة في بعض المناطق. هذه معلومة عامة، وتُوجَّه الأسئلة حول معالجة المياه إلى الجهة المسؤولة." },
  { id: "w25", category: "water_context", keywords: ["chlorine", "smell", "treated", "كلور", "رائحه", "معالجه"],
    en: "A chlorine-like smell can occur where water is treated. The survey records whether residents notice smell or taste; it does not give health advice.",
    ar: "قد تظهر رائحة شبيهة بالكلور حيث تُعالَج المياه. ويسجّل الاستبيان ما إذا كان السكان يلاحظون رائحة أو طعمًا؛ وهو لا يقدّم نصائح صحية." },
  { id: "w26", category: "water_context", keywords: ["how long", "duration", "outage", "كم", "مده", "انقطاع"],
    en: "How long a water cut-off lasts can vary, and this assistant cannot predict or guarantee timing. Reporting when an outage started helps services understand it.",
    ar: "قد تختلف مدة انقطاع المياه، ولا يستطيع هذا المساعد التنبؤ بالتوقيت أو ضمانه. والإبلاغ عن وقت بدء الانقطاع يساعد الجهات على فهمه." },
  { id: "w27", category: "water_context", keywords: ["planned", "maintenance", "unplanned", "burst", "صيانه", "مخطط", "كسر"],
    en: "Some interruptions are planned (for maintenance) and some are unplanned (such as a burst pipe). Knowing which it is can help residents understand what to expect.",
    ar: "بعض الانقطاعات مخطّطة (للصيانة) وبعضها غير مخطّط (مثل كسر أنبوب). ومعرفة نوعه قد تساعد السكان على فهم ما يمكن توقّعه." },
  { id: "w28", category: "water_context", keywords: ["after report", "what happens", "response", "outcome", "بعد الإبلاغ", "استجابه", "نتيجه"],
    en: "After a water issue is reported, the responsible service decides how and when to respond. Neither the survey nor this assistant can guarantee an outcome or a timeline.",
    ar: "بعد الإبلاغ عن مشكلة مياه، تقرر الجهة المسؤولة كيفية وزمن الاستجابة. ولا يستطيع الاستبيان ولا هذا المساعد ضمان نتيجة أو جدول زمني." },
  { id: "w29", category: "water_context", keywords: ["treat", "boil", "make safe", "purify", "معالجه", "غلي", "تنقيه", "صالح للشرب"],
    en: "Questions about making water safe to drink should go to the responsible water authority. This assistant does not give health, treatment, or boiling advice.",
    ar: "تُوجَّه الأسئلة حول جعل المياه صالحة للشرب إلى الجهة المسؤولة عن المياه. ولا يقدّم هذا المساعد نصائح صحية أو عن المعالجة أو الغلي." },
  { id: "w30", category: "water_context", keywords: ["shortage", "what can i do", "preserve", "conserve", "saving", "awareness", "ندره", "ماذا افعل", "ترشيد", "توعيه"],
    en: "Water shortages can make daily water use difficult. This assistant gives general information only and cannot provide official conservation instructions or personalised advice. The project collects general feedback about shortages, leaks, and interruptions.",
    ar: "يمكن أن يجعل نقص المياه الاستخدام اليومي صعبًا. يقدّم هذا المساعد معلومات عامة فقط ولا يقدّم تعليمات رسمية لترشيد المياه أو نصائح شخصية. ويجمع المشروع آراء عامة حول النقص والتسربات والانقطاعات." },

  // ── added: deeper digital-tools coverage ──
  { id: "d21", category: "digital_tools_context", keywords: ["account", "sign up", "register", "حساب", "تسجيل", "اشتراك"],
    en: "Some digital tools ask you to create an account, while others let you report without one. Needing an account can be a barrier for some people, which the survey explores.",
    ar: "تطلب بعض الأدوات الرقمية إنشاء حساب، بينما تتيح أخرى الإبلاغ دون حساب. وقد يكون اشتراط الحساب عائقًا لبعض الناس، وهو ما يستكشفه الاستبيان." },
  { id: "d22", category: "digital_tools_context", keywords: ["free", "cost", "data", "charge", "مجاني", "تكلفه", "بيانات"],
    en: "Apps themselves are often free to install, but using them still uses mobile data, which has a cost. Data cost is a barrier the project asks about.",
    ar: "غالبًا ما تكون التطبيقات مجانية التثبيت، لكن استخدامها يستهلك بيانات الهاتف التي لها تكلفة. وتكلفة البيانات عائق يسأل عنه المشروع." },
  { id: "d23", category: "digital_tools_context", keywords: ["one language", "translation", "لغه واحده", "ترجمه"],
    en: "A tool available in only one language is harder for people who do not read that language. Language support is one of the accessibility issues the survey examines.",
    ar: "الأداة المتوفرة بلغة واحدة فقط أصعب على من لا يقرأ تلك اللغة. ودعم اللغة أحد قضايا سهولة الوصول التي يبحثها الاستبيان." },
  { id: "d24", category: "digital_tools_context", keywords: ["voice", "audio", "speak", "صوت", "صوتيه", "قراءه"],
    en: "Voice messages or audio options can help people who find reading and writing difficult. Whether tools offer such options is relevant to accessibility.",
    ar: "قد تساعد الرسائل الصوتية أو خيارات الصوت من يجدون صعوبة في القراءة والكتابة. ومدى توفير الأدوات لهذه الخيارات وثيق الصلة بسهولة الوصول." },
  { id: "d25", category: "digital_tools_context", keywords: ["alert", "notification", "subscribe", "تنبيه", "إشعار", "اشتراك"],
    en: "Some services send outage or schedule alerts by SMS or app notification. Whether residents receive and understand such alerts is part of the survey.",
    ar: "ترسل بعض الجهات تنبيهات الانقطاع أو الجدول عبر الرسائل النصية أو إشعارات التطبيق. ومدى تلقّي السكان لهذه التنبيهات وفهمها جزء من الاستبيان." },
  { id: "d26", category: "digital_tools_context", keywords: ["opt out", "unsubscribe", "stop messages", "إلغاء", "إيقاف الرسائل"],
    en: "People may want to stop receiving messages they did not ask for. Good tools make it clear how to opt out; this is a general design point, not specific to any service.",
    ar: "قد يرغب الناس في إيقاف تلقّي رسائل لم يطلبوها. وتوضّح الأدوات الجيدة كيفية إلغاء الاشتراك؛ وهذه نقطة تصميم عامة وليست خاصة بجهة معيّنة." },
  { id: "d27", category: "digital_tools_context", keywords: ["link", "qr", "scam", "رابط", "رمز", "احتيال"],
    en: "Be careful with links or QR codes from unknown sources, and do not enter personal details into pages you do not trust. Keep digital reports general and avoid sharing private information.",
    ar: "كن حذرًا مع الروابط أو رموز QR من مصادر غير معروفة، ولا تُدخِل تفاصيل شخصية في صفحات لا تثق بها. أبقِ البلاغات الرقمية عامة وتجنّب مشاركة المعلومات الخاصة." },
  { id: "d28", category: "digital_tools_context", keywords: ["help", "family", "assist", "مساعده", "عائله", "احد"],
    en: "It is fine to ask a family member or friend to help use a digital tool. Needing help is common and is one of the access factors the survey considers.",
    ar: "لا بأس بطلب المساعدة من أحد أفراد العائلة أو الأصدقاء لاستخدام أداة رقمية. والحاجة إلى المساعدة شائعة وأحد عوامل الوصول التي يأخذها الاستبيان في الاعتبار." },

  // ── added: deeper project coverage ──
  { id: "p16", category: "project_context", keywords: ["how long", "time", "length", "questions", "كم", "مده", "أسئله"],
    en: "The survey is short and made up of a small set of questions, with an optional comment in each theme. You can stop at any point.",
    ar: "الاستبيان قصير ويتكوّن من مجموعة صغيرة من الأسئلة، مع تعليق اختياري في كل محور. ويمكنك التوقف في أي لحظة." },
  { id: "p17", category: "project_context", keywords: ["who", "eligible", "refugees", "participate", "من", "يشارك", "لاجئين"],
    en: "The project first focuses on refugees in Jordan and later extends to other communities. Taking part is voluntary and open to residents the project invites.",
    ar: "يركّز المشروع أولًا على اللاجئين في الأردن ثم يمتد لاحقًا إلى مجتمعات أخرى. والمشاركة طوعية ومتاحة للسكان الذين يدعوهم المشروع." },
  { id: "p18", category: "project_context", keywords: ["change", "improve", "will it help", "guarantee", "تغيير", "تحسين", "وعد"],
    en: "The project studies experiences with water technology; it cannot promise that taking part will change your water service. Its value is in informing research and future work.",
    ar: "يدرس المشروع التجارب مع تكنولوجيا المياه؛ ولا يمكنه أن يَعِد بأن المشاركة ستغيّر خدمة المياه لديك. وتكمن قيمته في إفادة البحث والعمل المستقبلي." },
  { id: "p19", category: "project_context", keywords: ["paid", "payment", "money", "reward", "مقابل", "دفع", "مكافأه"],
    en: "Participation is voluntary and there is no payment for taking part. The survey is for research, not a service or benefit application.",
    ar: "المشاركة طوعية ولا يوجد مقابل مادي للمشاركة. والاستبيان لأغراض البحث وليس طلبًا لخدمة أو منفعة." },
  { id: "p20", category: "project_context", keywords: ["again", "multiple", "twice", "repeat", "مره اخري", "تكرار", "عده مرات"],
    en: "The survey is meant to be completed once per person so the research stays meaningful. There is no benefit to submitting it many times.",
    ar: "يُقصَد إكمال الاستبيان مرة واحدة لكل شخص حتى يبقى البحث ذا معنى. ولا فائدة من إرساله عدة مرات." },
  { id: "p21", category: "project_context", keywords: ["language", "arabic", "english", "switch", "لغه", "عربيه", "إنجليزيه"],
    en: "The survey and this assistant support Arabic and English, and you can use whichever you prefer. The survey lets you choose your language.",
    ar: "يدعم الاستبيان وهذا المساعد العربية والإنجليزية، ويمكنك استخدام ما تفضّله. ويتيح لك الاستبيان اختيار لغتك." },
  { id: "p22", category: "project_context", keywords: ["are you human", "real person", "bot", "automated", "إنسان", "شخص", "آلي"],
    en: "This assistant is an automated information tool, not a person. It shares general approved information and cannot take actions on your behalf.",
    ar: "هذا المساعد أداة معلومات آلية وليس شخصًا. يقدّم معلومات عامة معتمدة ولا يمكنه اتخاذ إجراءات نيابةً عنك." },
  { id: "p23", category: "project_context", keywords: ["connect", "fix", "complaint", "contact company", "ربط", "إصلاح", "شكوي"],
    en: "This assistant cannot connect you to a water company, open a complaint, or fix a water problem. For a specific issue, contact your water provider through their official channels.",
    ar: "لا يستطيع هذا المساعد ربطك بشركة مياه أو فتح شكوى أو إصلاح مشكلة مياه. وللمشكلات المحددة، تواصل مع مزوّد المياه عبر قنواته الرسمية." },

  // ── added: deeper confidentiality coverage ──
  { id: "c13", category: "confidentiality_context", keywords: ["personal information", "what counts", "identify", "معلومات شخصيه", "ما هي", "تعريف"],
    en: "Personal information includes your name, phone number, exact address, ID or registration numbers, and similar identifying details. Please keep these out of your answers.",
    ar: "تشمل المعلومات الشخصية اسمك ورقم هاتفك وعنوانك الدقيق وأرقام الهوية أو التسجيل والتفاصيل المعرّفة المشابهة. يُرجى إبقاؤها خارج إجاباتك." },
  { id: "c14", category: "confidentiality_context", keywords: ["location", "gps", "track", "موقع", "تتبع", "عنوان"],
    en: "The survey does not track your GPS location or collect your exact address. A general area, such as a city or district, is all that is used.",
    ar: "لا يتتبّع الاستبيان موقعك عبر GPS ولا يجمع عنوانك الدقيق. وكل ما يُستخدم هو منطقة عامة مثل مدينة أو حي." },
  { id: "c15", category: "confidentiality_context", keywords: ["encryption", "encrypted", "protected", "تشفير", "حمايه", "محمي"],
    en: "Collected answers are protected in transit and in storage, and are accessible only to the authorised research team.",
    ar: "تُحمى الإجابات المجمّعة أثناء النقل وفي التخزين، ولا يطّلع عليها سوى فريق البحث المخوّل." },
  { id: "c16", category: "confidentiality_context", keywords: ["how long kept", "retention", "store", "delete", "كم تحفظ", "الاحتفاظ", "حذف"],
    en: "Data is kept only as long as the research needs it, under the research team's retention policy, and is then deleted or fully anonymised. This assistant does not set or know exact dates.",
    ar: "تُحفظ البيانات فقط طالما يحتاجها البحث، وفق سياسة الاحتفاظ لدى فريق البحث، ثم تُحذف أو تُجرَّد من الهوية بالكامل. ولا يحدّد هذا المساعد التواريخ الدقيقة ولا يعرفها." },
  { id: "c17", category: "confidentiality_context", keywords: ["withdraw", "remove", "after submit", "delete my", "سحب", "إزاله", "بعد"],
    en: "If you change your mind after taking part, you can ask the research team to remove your responses. The thank-you page explains how to get in touch.",
    ar: "إذا غيّرت رأيك بعد المشاركة، يمكنك أن تطلب من فريق البحث إزالة إجاباتك. وتوضّح صفحة الشكر كيفية التواصل." },
  { id: "c18", category: "confidentiality_context", keywords: ["optional", "gender", "prefer not", "skip demographic", "اختياري", "النوع", "تخطي"],
    en: "Demographic questions, including gender, are optional and offer a 'prefer not to say' choice. You can skip any you are not comfortable answering.",
    ar: "الأسئلة الديموغرافية، بما فيها النوع الاجتماعي، اختيارية وتتيح خيار 'أفضّل عدم الإجابة'. ويمكنك تخطّي أي منها لا ترتاح للإجابة عنه." },
];
